version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: canvas
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
  postgres-test:
    image: postgres:12
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: template1
    ports:
      - 5433:5432
  elasticmq-test:
    image: softwaremill/elasticmq-native
    ports:
      - 9326:9324
volumes:
  postgres:
