global:
  scrape_interval: 15s
  external_labels:
    container: ${HOSTNAME}

scrape_configs:
  - job_name: app
    basic_auth:
      username: prometheus
      password: "12345678"
    static_configs:
      - targets:
          - localhost:8080

remote_write:
  - url: https://example.com/push
    basic_auth:
      username: prometheus
      password: "12345678"
