{
 "title": "Canvas",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, path, code) (\n  rate(app_http_requests_total[$__rate_interval]) > 0\n)",
     "legendFormat": "{{method}} {{path}} {{code}}"
    }
   ]
  },
  {
   "title": "Request durations",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(app_http_request_duration_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (name, success) (\n  rate(app_jobs_total[$__rate_interval])\n)",
     "legendFormat": "{{name}} success:{{success}}"
    }
   ]
  },
  {
   "title": "Job runner",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (success) (\n  rate(app_job_runner_receives_total[$__rate_interval])\n)",
     "legendFormat": "success:{{success}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(go_sql_max_open_connections)"
    },
    { "expr": "sum(go_sql_open_connections)" },
    { "expr": "sum(go_sql_idle_connections)" },
    { "expr": "sum(go_sql_in_use_connections)" },
    {
     "expr": "sum(increase(go_sql_wait_count_total[$__rate_interval]))"
    }
   ]
  }
 ]
}